cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: true

globalFolder: ./.yarn/cache/global

nodeLinker: pnpm

packageExtensions:
  prettier-eslint@*:
    dependencies:
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
