cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: true

globalFolder: ./.yarn/cache/global

nodeLinker: pnpm

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@mincho-js/*"

npmAuditExcludePackages:
  - "deep-diff" # Deprecated but still functional, used by @mincho-js/debug-log

packageExtensions:
  prettier-eslint@*:
    dependencies:
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
