cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: true

globalFolder: ./.yarn/cache/global

nodeLinker: pnp

pnpFallbackMode: none

pnpMode: strict

npmAuditExcludePackages:
  - deep-diff

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@mincho-js/*"
  - "@turbo/*"
  - turbo

packageExtensions:
  next@16.2.6:
    peerDependencies:
      next-rspack: "16.2.6"
    peerDependenciesMeta:
      next-rspack:
        optional: true
  nextra@*:
    peerDependencies:
      typescript: "*"
  prettier-eslint@*:
    dependencies:
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
