name: Feature from RFC
description: Feature item from RFC
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: RFC feature description
      description: A clear and concise description of the specific feature mentioned in the RFC.
      placeholder: Ex. Nested Properties is a feature in CSS that groups related properties to improve code readability and reduce redundancy
    validations:
      required: true

  - type: input
    id: related-rfc
    attributes:
      label: Related RFC
      description: Related RFC in the [working group](https://github.com/mincho-js/working-group).
      placeholder: Paste the RFC link
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: The solution I'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or video
      description: It is helpful to attach screenshots or video similar to the desired features.
      placeholder: You can drag & drop to attach files
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives I've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: It would be great if you have a relevant image or link
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Anything to write down or refer to is fine
    validations:
      required: false
