name: Check skip action
description: Skip action if the same content was already run

# https://github.com/fkirc/skip-duplicate-actions
runs:
  using: composite
  steps:
    - uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: same_content_newer
        skip_after_successful_duplicate: "true"
        paths_ignore: '["**/README.md"]'
