name: Setup
description: Node.js setup for CI/CD

inputs:
  strict:
    description: Paths to cache
    required: false
    default: "true"

runs:
  using: composite
  steps:
    # https://github.com/actions/cache/blob/main/examples.md#node---yarn
    # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        corepack enable
        echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          .yarn/unplugged
          .yarn/build-state.yml
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Package Install
      run: |
        yarn config set winLinkType symlinks
        if [ "${{ inputs.strict }}" = "true" ]; then
          echo "Installing with strict mode"
          yarn install --immutable --check-resolutions --refresh-lockfile
          echo "Checking peerDeps and constraints"
          yarn check:pkgs
          echo "Running npm audit"
          yarn npm audit --all 
        else
          YARN_ENABLE_HARDENED_MODE=0 yarn install --no-immutable
        fi
      shell: bash
