name: CI

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check SkipAction
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md"]'

  dependencies:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/node-setup

      - name: Project Reference Check
        run: yarn sync:check

  typecheck:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/node-setup
        with:
          strict: false

      - name: More setup cache
        uses: ./.github/actions/cache-dir
        with:
          key: install-and-check
          paths: |
            .cache
            **/.cache
            dist
            **/dist

      - name: Typechecker
        run: yarn build:type

      - name: Lint & format
        run: |
          ## Require type build
          # https://typescript-eslint.io/getting-started/typed-linting/
          yarn lint

  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/node-setup
        with:
          strict: false

      - name: More setup cache
        uses: ./.github/actions/cache-dir
        with:
          key: build-and-test

      - name: Test
        run: yarn test
