name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/fast-forward') }}
    runs-on: ubuntu-latest
    concurrency:
      group: fast-forward-${{ github.event.issue.number }}
      cancel-in-progress: true

    # https://docs.github.com/ko/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Check comment
        id: check_comment
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT_BODY" =~ (^|[[:space:]])/fast-forward($|[[:space:]]) ]]; then
            echo "MATCH=true" >> $GITHUB_OUTPUT
          else
            echo "MATCH=false" >> $GITHUB_OUTPUT
          fi

      - name: Fast forwarding
        if: ${{ steps.check_comment.outputs.MATCH == 'true' }}
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always
